branches:
  only:
  - master
install:
- echo "Skipping install."
script:
- echo "Skipping build. Deploying site to S3"
deploy:
  provider: s3
  region: eu-west-2
  access_key_id: AKIAJ4VWRMHM3HA5GKIA
  secret_access_key:
    secure: V9Ea5Cjs0ao5W45n54/2vtO74rWCSXk0dCB/AgqiGBBpASwMqOmivL93R/cduxUjMXX2BhKypesDlWf6fUXPoXQ1Dw2KNcGUmzxrVpVLoZ6tGDQauKSWf8lLdYVADZYtXjZbWgKDF/hQ95ApejfPx1M6wUdiYN7Or2i7RPIiBoiP9hfn3tFVcb3RWE72rH2ya5PKevE7Lx0wX1MkYUf/8T+m01FEPUGzqdnn5tNn4x0d0I+pxl7x0EbO7ABrPqcq0Nr0qDsTBDVigIznBdngIorJc4LThRwWv4nBNAbDJ6PkJcCl5ssUoCZ2Ni1JL6w6QKehGirGc/aWaNpTa4po8SZ6K1Pl/Ytp2xtNGN4Gu4tGAGYpUxv+pWvO4P6TLiX6E+M5WoHwwKQtttgiLJn4dl7LMuPQKJp57uoqD2pXnl8uyApzx3UhR+d6AiAmzTTUXp7XwEB4NW+lavJOOaMiTnQLcnXnT3iO+xE/v4kj7m5yV0HXebESus3+Nit1luIh1URKwImhOHXPuuzK7X3HA1f/3UMpzBjc9gHmde44GXzPOGCnVmRqkpLJY5hBUvM+ATv6ruxKT6Qvr7L21E44mYTd2t3QfhjMToonidfjBW3fmgHnmIqKMlUVIBnRMCLIHg0SvtMYhUhBdg5nE0SwGP325cZay9GPFN6Pd5yLWow=
  bucket: hackerman-2003.xyz
  on:
    repo: RossSingleton/rossweb